### ISSUE TITLE
Multiple users in the same city don't show up

### ISSUE THREAD

**Issue by Sopamo** [PHPMap/PHPMap#11]
It seems like all users in the same city have the marker at exactly the same positions, which makes it so that you only see the marker of the last user.
Maybe we should add a little bit of random to the markers which have a very general location (like Berlin)?

**Comment by fwartner** [comment]
This is an issue, when users sign up but only with their City.. Streetname is recommended.. ^^

**Comment by Sopamo** [comment]
Yeah but that doesn't help, because a lot of users don't add their street name :) You'd either have to make that very clear, that you need to specify your street name or users will think that's a bug (which it is imo) because they can't find themselves on the map

**Comment by fwartner** [comment]
I created a reminder for users that don´t have an address in their profile.. Otherwise they won´t be shown on the map.. I have to deal with some more issues soon ^^ 

(Kannst mir gerne helfen :) )

**Comment by Sopamo** [comment]
Okay, how about searching for all markers which are on the same location and add some randomness to them so all of them are shown?
I could implement that maybe later today.

**Comment by fwartner** [comment]
Great idea.. Create an PR and i will look over it! :)
