### ISSUE TITLE
Bangkok wrongly located

### ISSUE THREAD

**Issue by pierrejoye** [PHPMap/PHPMap#18]
Small issue but Bangkok/Thailand shows the wrong location.

**Comment by fwartner** [comment]
Go to your profile settings and try to change it...

**Comment by pierrejoye** [comment]
I did :)

I did not check what GitHub gives with the profile api call. Maybe the
issue is in their side?

**Comment by fwartner** [comment]
GitHub doesn't provide lat and lng values.
