### ISSUE TITLE
Add some CI tools to the repo

### ISSUE THREAD

**Issue by svenluijten** [PHPMap/PHPMap#21]
I'd propose to add some CI tools to the repo to automatically check code integrity whenever a new PR is made. If we don't have these, I can see the codebase of this project quickly turning into something we have to hold together with band-aids and duct-tape.

Proposed tools:
- [StyleCI](https://styleci.io) - Keep coding style uniform and check the style of a PR when it it made.
- [Travis CI](https://travis-ci.org) - Run tests automatically (we'd need tests for this though :stuck_out_tongue:) and whenever a new PR is made.

**Comment by svenluijten** [comment]
We can also use [Nitpick CI](https://nitpick-ci.com) in favor of StyleCI, but I've not worked with Nitpick before. Your call :smile:

**Comment by fwartner** [comment]
I would like to use StyleCI.. Will open up the account this evening, when i´m back home.
