### ISSUE TITLE
Do not send password in plain text via email

### ISSUE THREAD

**Issue by BinaryKitten** [PHPMap/PHPMap#22]
After registering with Github, i was emailed my "temporary password" in plain text.

No email should have password, no matter how temporary.

**Comment by Sopamo** [comment]
The password you are seeing is purely to allow users to login independent from the Github API.
You might have a point that passwords should not be sent in plain text, but in this case we are trading a very small security risk (we are not talking about your bank account after all) for increased usability which is okay for us. 
You are free to change your password at any time after you created your account.
