### ISSUE TITLE
Addition for CONTRIBUTION.md:

### ISSUE THREAD

**Issue by fwartner** [PHPMap/PHPMap#28]
Make clear, that contributors have to do ```gulp --production``` ^^

**Comment by svenluijten** [comment]
do you think this should happen in the same commit or a different one? Eg:
```
- add something to app.js
- compile assets
```
or
```
- add something to app.js
```
with the assets already compiled?

**Comment by svenluijten** [comment]
added [here](https://github.com/PHPMap/PHPMap/commit/0bda0b8cf7a670f1c84633f1e77802363e7ca87d). Might wanna take a look and reword that to your liking @fwartner. For now, I think it's a good start. :smiley:
