### ISSUE TITLE
Changing the username (or clarifying how its used)

### ISSUE THREAD

**Issue by sunscreem** [PHPMap/PHPMap#29]
During registration it would be good to know the "Username" is the name that will be displayed on the map.

It might be obvious but, I'm dumb, and didn't think it through - now I can't change it :(

**Comment by fwartner** [comment]
Use the support widget and i will help you :)

**Comment by sunscreem** [comment]
Its okay @fwartner .. It can stay as my nickname. Just good to let others know. Maybe instead of `username` on the registration form you could use `display name`?

**Comment by fwartner** [comment]
Good idea. Will change it now. Thanks :)
