### ISSUE TITLE
Temporary password for social login is predictable

### ISSUE THREAD

**Issue by mattbit** [PHPMap/PHPMap#3]
Hi! Thank you for the great project.

I found that the temporary password set upon the social login is predictable (you just need to know the username, which is public information).

See the code here: https://github.com/PHPMap/PHPMap/blob/cfff45771d06c947b4db21cfdb5420f3dd3bee2f/app/Http/Controllers/Auth/SocialController.php#L66

The generated password should be random. Using Laravel helper `str_random` (which is based on `random_bytes`) should be enough to get a cryptographically secure random string.

**Comment by fwartner** [comment]
Will be fixed in the next update.. Thanks! :)
