### ISSUE TITLE
Delete my account please

### ISSUE THREAD

**Issue by ThaDafinser** [PHPMap/phpmap#30]
## Actual behavior:
Generate a password with the mail address and static prefix/suffix?
https://github.com/PHPMap/phpmap/blob/master/app/Jobs/Importers/MigrateUsers.php#L38

Password reset is a 404 page
https://phpmap.co/account/password

## Proposed solution:
- do a real password reset
- let the users change the password

**Comment by asgrim** [comment]
Wow. Seriously, this is the WORST possible thing I have ever seen. On receiving the email, I'd assumed that at least the digits were randomised. This is really bad for security, come on.

**Comment by Brunty** [comment]
I've sent an email - but this is truly unacceptable.

There was a similar issue in the past with temporary passwords (I have the original email in my archives) - I can't quite believe that lessons weren't learned from the first time.

**Comment by asgrim** [comment]
Please also delete my account. Sorry, but I can't trust my personal data with a site that cannot keep it's users safe, regardless of whether it's open source (PR or stfu) or not. Especially if what @Brunty says is right and this is a repeat incident...

**Comment by lbausch** [comment]
Yeah, I want to see my account deleted as well.

**Comment by Brunty** [comment]
Likewise, delete mine. As per my email request.

**Comment by Brunty** [comment]
Found it, here it is on the old site:

https://github.com/PHPMap/PHPMap-OLD/blob/602a7a545e49afc5986b29a19de21ab08dd27274/resources/views/emails/users/social_welcome_email.blade.php

**Comment by Luciam91** [comment]
Like the above, delete my account please. This is just plain scary...

**Comment by joshbrw** [comment]
Please remove my account, also. This is disappointingly bad security.

**Comment by Hodgy** [comment]
Please remove my account as well.

**Comment by fwartner** [comment]
Will be done tomorrow... sorry 😐

**Comment by lbausch** [comment]
Any progress on this?

**Comment by fwartner** [comment]
Again.. I´m sorry for that! :(

Here´s a link to delete your account: https://phpmap.co/account/delete

**Comment by Brunty** [comment]
It's been a while, but @fwartner I've just tried the account delete link, it's broken - I just get a 500 response.

Also your password reset form allows for account enumeration as it tells me when an email doesn't exist in the system: https://www.troyhunt.com/understanding-account-enumeration-the-video-tutorial-edition/

**Comment by fwartner** [comment]
Please create a PR.

**Comment by Brunty** [comment]
@fwartner and what about the 500 delete account issue?

**Comment by joshbrw** [comment]
@fwartner I'm displeased with how you're handling this issue. We want our accounts permanently erased from your system, and telling us to Create a PR simply isn't good enough at this point.
