### ISSUE TITLE
Search result dropdown shows plain template var instead of its value.

### ISSUE THREAD

**Issue by hollodotme** [PHPMap/phpmap#43]
## Expected behavior:

Search result dropdown should show the actual query.

## Actual behavior:

Search result dropdown shows "{{{ query }}}" instead.

![image](https://user-images.githubusercontent.com/1557839/27486742-d7ad989c-5831-11e7-83af-df3369313c72.png)

## Steps to reproduce the behavior:

Type e.g. "blubber" in the search field.

## Proposed solution:

Fix escaping of template var "query" in search result dropdown.

**Comment by fwartner** [comment]
Feel free to fork and create a PR for this! :)
