### ISSUE TITLE
Default migration doesn't work

### ISSUE THREAD

**Issue by PovilasKorop** [PHPMap/phpmap#48]
## Expected behavior:
Running `artisan migrate` on fresh install should succeed.

## Actual behavior:
It fails with error:
```
[Illuminate\Database\QueryException]                                                      
  SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'is_sponsor' (SQL: al  
  ter table `users` add `is_sponsor` tinyint(1) not null default '0') 

```
## Steps to reproduce the behavior:
Clone the project and run `artisan migrate`

## Proposed solution:
Delete the file `database/migrations/2017_05_05_111247_add_sponsor_to_users_table.php` cause it duplicates the very first migration file for creating users - field `is_sponsor` is created there.

**Comment by fwartner** [comment]
Please create a PR for this.
